### PR TITLE
added user routes and functions

### PR DESCRIPTION
**Pull request by HellenMelon**
Added user CRUD to create, get, update and delete user.

### CODE REVIEW

**Comment by aidenrawles** [comment]
For the routes, have the whole function written in the controllers rather than the routes. I forgot to mention this before. So, it should look like this in the routes: Example:
`router.get('/create', userCreate)`

Then in the controllers u will have:
`const userCreate = async (req, res) => {
};`

**Review by aidenrawles — CHANGES_REQUESTED** [review]
Great work, just made a comment with some formatting changes.

**Review by gudluckman — COMMENTED** [review]
Yep, i agree with Aiden. Once that changes have been made, would be good to merge

**Review by gudluckman — APPROVED** [review]
Yep, LGTM

**Review by aidenrawles — APPROVED** [review]

**Pull request merged**
